# Generated by Django 5.0 on 2024-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('surat', models.ImageField(upload_to='static/images')),
                ('diccription', models.TextField()),
                ('quantify', models.IntegerField()),
            ],
        ),
    ]
