# Generated by Django 5.0 on 2024-10-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='Zaftra', max_length=50),
        ),
    ]
